# PDF Extractor Configuration File
# See documentation for detailed explanation of options

# Extraction modes: standard, detailed, fast
mode: standard

# Output formats: hierarchical, flat, raw
format: hierarchical

# Feature flags
extract_images: false
extract_tables: true
preserve_layout: false
validate_schema: true

# Processing settings
verbose: false

# Advanced settings
image_extraction_threshold: 0.5
table_extraction_method: pymupdf
text_cleaning_level: standard

# Performance settings
max_memory_mb: 512
parallel_processing: false
